### ISSUE TITLE
Implement the ability to make new config files from interface

### ISSUE THREAD

**Issue by Conr86** [SFXRescue/SIGHTSInterface#21]
Currently the only way to make a new config file is through the SSH interface. A simple **New Config** file button would suffice (with a popup text box or something to set the name). Perhaps also a rename button actually, now that I think about it.

This will likely require additional functions in `supervisor_sart_config` which is cool. Probably a `createConfig(filename)` and `renameConfig(oldfilename, new_filename)` function.

**Comment by WilliamsJack** [comment]
A "Save as" button might be a nice way to achieve this. That way the user can edit their existing config and then decide to save their changes over their existing config with the `Save` button or as a new config with `Save as`. This means we don't have to populate the editor with new data and we don't need to keep track of whether the user is editing a new file or an existing one (since we only get that information when we need to save it).

On the topic of saving, the existing `save_config` function in the ControlReceiver class could take care of this. If given another argument `file_name`, it could save a new file if none exists or perform the existing rolling backup code if it does.

**Comment by Conr86** [comment]
Good thinking! Definitely a good way to do this. Would you also want a delete config button? And in that case, how do we handle it?

**Comment by WilliamsJack** [comment]
Hmm, I didn't think of that, but it's a good idea. Will `Delete` delete the currently active config?
I'd say the receiver can still do it, we'd just need a new command - unless you had a different way in mind?

Both `Save as` and `Delete` could automatically refresh the config list dropdown.

**Comment by Conr86** [comment]
I feel like it would be easier and safer to only allow the user to delete non-active configs. This means there is always at least one valid config file.

We could probably have either a separate "Delete Config" pop up menu with a basic list of configs with a delete button for all but the active config, or (it's probably not possible, but) integrate it into the config selector like this (excuse the ms paint):
![image](https://user-images.githubusercontent.com/5257675/68558569-f5dca780-048d-11ea-9724-8e740b73ff85.png)

**Comment by WilliamsJack** [comment]
That would be much better. It's definitely possible to add a button to a dropdown, but I think we'd have to make our own rather than using the `<select>` tag.

**Comment by WilliamsJack** [comment]
Created a new feature request for deleting. Seems appropriate to track it separately since this issue will be closed once the save-as branch is merged.
